function graphics_startup_parpool
    graphic_reset(15, ...
        'DefaultAxesMinorGridAlpha', 0.05, ...
        'DefaultAxesMinorGridLineStyle', '-', ...
        'DefaultTextInterpreter', 'latex', ...
        'DefaultLegendInterpreter', 'latex', ...
        'DefaultStemMarkerSize', 1, ...
        'DefaultStemlineWidth', 1.5);
end