%% Example start up scripts to call before every script

addpath(genpath('functions'));
addpath(genpath('../matlab-ext'));

% Reset default graphic options 
graphic_setdefault(15, ...
    'DefaultAxesMinorGridAlpha', 0.05, ...
    'DefaultAxesMinorGridLineStyle', '-', ...
    'DefaultTextInterpreter', 'latex', ...
    'DefaultLegendInterpreter', 'latex', ...
    'DefaultStemMarkerSize', 1, ...
    'DefaultStemlineWidth', 1.5);

% Any additional settings
% set(0, 'DefaultFigureWindowStyle','docked');
